services:
  ### Metrics ###
  prometheus:
    image: prom/prometheus:latest
    container_name: popfilms_prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./monitoring/prometheus/prometheus-alerts.yaml:/etc/prometheus/prometheus-alerts.yml
    ports:
      - "9090:9090"
    networks:
      - app-network
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=10d"
      - "--storage.tsdb.retention.size=2GB"
  alertmanager:
    image: prom/alertmanager:latest
    container_name: popfilms_alertmanager
    networks:
      - app-network
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring/alertmanager/alertmanager.yaml:/etc/alertmanager/alertmanager.yml

  grafana:
    image: grafana/grafana-oss:latest
    container_name: popfilms_grafana
    ports:
      - "5000:3000"
    depends_on:
      prometheus:
        condition: service_started
    networks:
      - app-network
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/dashboard-files:/var/lib/grafana/dashboards
      - ./monitoring/grafana/grafana.ini:/etc/grafana/grafana.ini
    env_file:
      - .env
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - app-network

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    container_name: popfilms_blackbox
    ports:
      - "9115:9115"
    networks:
      - app-network
    volumes:
      - ./monitoring/blackbox/blackbox.yaml:/etc/blackbox_exporter/config.yml
    command:
      - "--config.file=/etc/blackbox_exporter/config.yml"

  ### Databases ###
  db:
    image: postgres:17
    container_name: popfilms_db
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - app-network
  minio:
    image: minio/minio:latest
    container_name: popfilms_minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
      - ./testdata/minio:/testdata
    ports:
      - "9000:9000"
    networks:
      - app-network
  redis:
    image: redis:alpine
    container_name: popfilms_redis
    volumes:
      - redis_data:/data
    networks:
      - app-network

  ### Microservices ###
  backend-http:
    container_name: popfilms_backend-http
    image: "ghcr.io/sorrtory/popfilms-backend:latest"
    env_file:
      # - "./configs/http.env"
      - .env
    ports:
      - "8080:8080"
      - "8880:8880"
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - app-network
    entrypoint: ["./http"]
  backend-auth:
    container_name: popfilms_backend-auth
    image: "ghcr.io/sorrtory/popfilms-backend:latest"
    env_file:
      - .env
    ports:
      - "8082:8082"
      - "8882:8882"
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - app-network
    entrypoint: ["./auth"]
  backend-search:
    container_name: popfilms_backend-search
    image: "ghcr.io/sorrtory/popfilms-backend:latest"
    env_file:
      - .env
    ports:
      - "8083:8083"
      - "8883:8883"
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - app-network
    entrypoint: ["./search"]
volumes:
  db_data:
  minio_data:
  redis_data:
  grafana_data:

networks:
  app-network:
    driver: bridge
